export { isContextError, type HospitalContext } from './context'
export { requireHospitalCapability } from './guard'
export { fetchModuleRegistry, gateHospitalModule, isHospitalModuleActive, type ModuleRegistryEntry } from './modules'
export { logHospitalAudit, requireHospitalAudit, HospitalAuditRequiredError } from './audit'
export { hospitalOutboxWrapMaterial } from './outbox-wrap'
